import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import ToasterProvider from "../provider/ToasterProvider";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blog Spot ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interFont.variable} antialiased`}>
        {children}
        <ToasterProvider />
      </body>
    </html>
  );
}
